resolves #6 implement asm translator with documentation
ryukzak/brainfuck pull request #7
Opened 2024-02-12 09:13 UTC by k1b24

Реализация транслятора asm 

Лазеев Сергей P33131

2024-02-12 16:29 UTC, ryukzak requested changes
In general -- looks well. But as education purpose I plan to significantly rewrite your code to be more simple after you finish these fixes.

I will call you for review my PR.

2024-02-12 16:29 UTC, ryukzak commented on python/README_asm.md
> +arg ::= integer
Do we really need `integer` here? label_name should be enough.

2024-02-12 16:29 UTC, ryukzak commented on python/README_asm.md
> +        | "jz" arg
```suggestion
instr ::= op0 
        | op1 arg
        
op0 ::= "increment" 
      | "decrement"
      | "right" 
      | "left"
      | "print" 
      | "input"
      
op1 ::= "jmp"
      | "jz"
```

2024-02-12 16:29 UTC, ryukzak commented on python/README_asm.md
> +line ::= [ label ] [ instr ] [ comment ] "\n"
To be more simple:

```suggestion
line ::= label: [ comment ] "\n"
       | instr [ comment ] "\n"
       | [ comment ] "\n"
```

2024-02-12 16:29 UTC, ryukzak commented on python/README_asm.md
> +Метки из программы исчезают, а на место обращений к ним подставляются конкретные адреса.
We need golden tests for the translator.

2024-02-12 16:29 UTC, ryukzak commented on python/README_asm.md
> +Метки из программы исчезают, а на место обращений к ним подставляются конкретные адреса.
Two paragraphs?

2024-02-12 16:29 UTC, ryukzak commented on python/translator_asm.py
> +    instrs = []
Rename to `code`, as in `translator.py`

2024-02-15 06:32 UTC, k1b24 commented
@ryukzak may you take a look, please

2024-02-17 11:03 UTC, ryukzak requested changes
Сделал вам ПР с рефакторингом: https://github.com/k1b24/brainfuck/pull/1

Можете если необходимо документацию обновить.

2024-02-17 13:45 UTC, k1b24 commented on python/integration_test.py
> +        assert lang == "bf" or lang == "asm"
It seems like this code will be a little bigger, if I get you right

`
lang = None
source = None
if "in_source_asm" in golden:
  lang = "asm"
  source = golden["in_source_asm"]
if "in_source" in golden:
  assert lang is None, "both in_source and in_source_asm are present"
  lang = "bf"
  source = golden["in_source"]
assert lang is not None, "either in_source xor in_source_asm must be set"
`

And in this case we also need to add some logic about referencing the `in_source` param on this line below:
`file.write(golden["in_source"])`

2024-02-17 13:48 UTC, k1b24 commented
Merged PR and fixed some typos in the documentation

2024-02-17 16:54 UTC, ryukzak requested changes

2024-02-17 16:54 UTC, ryukzak commented on python/integration_test.py
> +        assert lang == "bf" or lang == "asm"
```suggestion
        assert "in_source" in golden !=  "in_source_asm" in golden
```

2024-02-17 16:54 UTC, ryukzak commented on python/integration_test.py
> +        source = os.path.join(tmpdirname, "source." + lang)
```suggestion
        source = os.path.join(tmpdirname, "source")
```

No body see this files...

2024-02-17 16:54 UTC, ryukzak commented on python/integration_test.py
> +                translator_asm.main(source, target)
```suggestion
            if "in_source" in golden:
                with open(source, "w", encoding="utf-8") as file:
                    file.write(golden["in_source"])
                translator.main(source, target)
            elif ...
```

2024-02-17 16:54 UTC, ryukzak commented on python/integration_test.py
> +        assert lang == "bf" or lang == "asm"
Just an idea

2024-02-18 12:49 UTC, merged